# createPVC.yaml
apiVersion: v1
kind: PersistentVolumeClaim  # telling kubernetes what this is.
metadata:
  name: mongo-pvc  #  consistent naming convention prevents hiccups
spec:
  accessModes:  #  what kind of access permissions this has
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    # Space allocated for PVC 
  storageClassName: "demo-storage"  # the handle that PVC uses to reach the Storage class