# mongo-configmap.yaml   600152989 Ryan Speirs
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
immutable: false
data:
  username: admin1  # username for the admin account, this could also be stored in secret
  mongodb.conf: | # Configures MongoDB storage path and replica set for high availability, not it is a multi-line string here
    storage:
      dbPath: /data/db  
    net:
      bindIp: 0.0.0.0
      port: 27017
    replication:
        replSetName: "rs0"        
 