# mongo-secret.yaml  600152989 Ryan Speirs
apiVersion: v1
kind: Secret  # tells it that we're a secret
metadata:
  name: mongodb-secret 
immutable: false
type: Opaque
data:
  password: cGFzc3dvcmQxMjM= # "password123"