apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backup-pv-unique
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/data/mongo-backups-unique
