# mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: YWRtaW4x     # base64 for "admin1"
  mongo-password: cGFzc3dvcmQxMjM= # base64 for "password123"